### ISSUE TITLE
Mesh issues in the preview scene

### ISSUE THREAD

**Issue by dh7300** [keijiro/4DViewsTest2#5] opened 2020-09-22 05:31 UTC
https://youtu.be/7RFwCL5obso

The last question helped me a lot in studying this project.
However, an unexpected issue arose.
Please see the captured YouTube video. During playback, the mesh comes out weird once at a time.
How do I fix or find out about this issue?

**Comment by keijiro** [comment] 2020-09-22 06:03
That might be a synchronization issue between Alembic and HAP. I updated the KlakHAP package to fix the issue in the previous months. I think you can avoid the problem by updating the KlakHAP package to 1.0.18.

**Comment by keijiro** [comment] 2020-09-22 06:03
I'm closing this issue now. Please feel free to reopen it if it still reproduces.

**Closed as completed by keijiro** 2020-09-22 06:03 UTC
Labels: question

**Comment by dh7300** [comment] 2020-09-22 06:25
It was not updated to 1.0.18, so I updated it to 0.1.18 and tested it. Although the frequency of occurrence of issues has decreased, there are still issues where the mesh becomes weird.

**Comment by keijiro** [comment] 2020-09-22 06:34
Could you test the same scene for multiple times? If the glitch happens every time at the same point, it's an arithmetic error. That should be reported as a bug. If the glitch happens in a non-deterministic fashion, it might be a problem with the storage (disk drive access speed). In that case, you have to upgrade the computer to solve the problem.

**Comment by dh7300** [comment] 2020-09-22 06:48
I think it was a disk problem. The project was on the HDD, but when I moved it to SSD, the issue problem disappeared.
However, when I changed the value of the Speed ​​Multiplier in Timeline's Alemnic Track and Control Track from 1 to 0.5, an issue arises.

**Comment by keijiro** [comment] 2020-09-22 07:41
You also have to change the playback speed of the HAP video player.

**Comment by dh7300** [comment] 2020-09-22 08:28
Are you referring to the Speed ​​part of the HAP Player script?
It was fixed at 1, should I change it to 0.5?

**Comment by dh7300** [comment] 2020-09-22 08:38
Even the project with the Speed ​​Multiplier set to 1 suddenly started to have mesh issues.
Assuming that the modeling movement ends in one cycle, a mesh issue occurs about once when it runs 2-3 cycles.

**Comment by keijiro** [comment] 2020-09-22 12:49
It should be set to 0.5.

**Comment by dh7300** [comment] 2020-09-23 01:12
Is the mesh issue occurring once a disk performance issue? After switching to SSD, the issue was noticeably reduced, but it still occurs. If you have a higher performance computer, wouldn't this happen?

多くの質問をしたところ親切に答えてくれて、本当にありがとうございます。あなたのGitHub情報に多大な研究がされています。

**Comment by keijiro** [comment] 2020-09-23 01:25
It works well on my machine, I'm not sure what the requirements are though.

Please note that the main aim of this project is making VFX for offline rendering, so I haven't done extensive tests with real-time use cases.

**Comment by dh7300** [comment] 2020-09-23 01:40
<img width="437" alt="abc" src="https://user-images.githubusercontent.com/69621922/93954703-37fe9700-fd89-11ea-833c-d60d8f5f56ce.png">

I really would like one last question.
How is the Vertex Count of the Mesh Baker script in the Abcvfx object determined?
In the inspector view, it is 98304, but in the script it says 32768, so I am curious about the difference.

**Comment by keijiro** [comment] 2020-09-23 02:42
There is no restriction on this value. You can specify any value you wish. I chose `98304=256*(256+128)` because `32768=256*128` and `65536=256*256` were not dense enough.
